name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose up -d --build
    # - name: Load Data
    #   run: docker compose run --rm wp-cli node ./scripts/data-seed.mjs

  deploy_staging_job:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor == 'your_username' }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load Data
        run: docker compose run --rm wp-cli node ./scripts/data-seed.mjs

      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export DOCKER_HOST=tcp://$PLAY_WITH_DOCKER.direct.labs.play-with-docker.com:2375
            docker-compose down
            docker-compose pull
            docker-compose up -d

