name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose up -d --build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Data Seed
      run: docker compose run --rm wp-cli node ./scripts/data-seed.mjs

